version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vanda_portfolio
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vanda-network

  backend:
    build: ./backend
    container_name: laravel_backend
    restart: unless-stopped
    # No need to expose 9000 to the public if Nginx is handling it
    depends_on:
      - mysql_db
    networks:
      - vanda-network

  frontend:
    build:
      context: ./frontend
      # Pass the AWS IP here so it gets baked into the JS
      args:
        - VITE_API_URL=http://13.239.31.154/api/v1
    container_name: vue_frontend
    # We don't expose 5173 because we want Nginx to serve the static files on Port 80
    networks:
      - vanda-network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      # We use volumes_from or named volumes to share the build files
      - frontend_build:/var/www/frontend/dist
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - vanda-network

networks:
  vanda-network:
    driver: bridge

volumes:
  mysql_data:
  frontend_build: # This stores the compiled Vue files