version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vanda_portfolio
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vanda-network

  backend:
    build: ./backend
    container_name: laravel_backend
    restart: unless-stopped
    depends_on:
      - mysql_db
    networks:
      - vanda-network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://13.239.31.154/api/v1
    container_name: vue_frontend
    # Keep container alive so it can maintain the volume
    tty: true
    stdin_open: true
    volumes:
      - frontend_build:/usr/share/nginx/html
    # This ensures files are moved into the shared volume at runtime
    command: sh -c "cp -rp /app/dist/. /usr/share/nginx/html/ && tail -f /dev/null"
    networks:
      - vanda-network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - frontend_build:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - vanda-network

networks:
  vanda-network:
    driver: bridge

volumes:
  mysql_data:
  frontend_build: