version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vanda_portfolio
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: laravel_backend
    restart: always
    # If using PHP-FPM, port 9000 is correct. If using 'php artisan serve', use 8000.
    ports:
      - "8000:8000" 
    depends_on:
      - mysql_db
    networks:
      - portfolio-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # This is the "magic" line. On local, this is ignored. 
        # On AWS, this bakes the IP into your Vue build.
        - VITE_API_URL=http://13.239.31.154/api/v1
    container_name: vue_frontend
    # We don't strictly need port 5173 on the server because Nginx handles port 80
    networks:
      - portfolio-network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
      # Ensure these paths match your server structure
      - ./frontend/dist:/usr/share/nginx/html 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  mysql_data: