name: Vanda Portfolio CI/CD

on:
  push:
    branches: [ main ]

jobs:
  push-to-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend  # Ensure this folder exists in your GitHub repo
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/vanda-backend:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend # Ensure this folder exists in your GitHub repo
          # Use your AWS Elastic IP or Domain for the host
          build-args: VITE_API_URL=http://${{ secrets.AWS_HOST }}/api/v1
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/vanda-frontend:latest

  deploy-to-aws:
    needs: push-to-registry
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Create directory if it doesn't exist
            mkdir -p ~/vanda-portfolio
            cd ~/vanda-portfolio
            
            # Pull the latest code from GitHub so the docker-compose.yml is updated
            if [ -d ".git" ]; then git pull; else git clone git@github.com:${{ github.repository }}.git .; fi

            # Update the environment file
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            
            # Use modern 'docker compose'
            docker compose pull
            docker compose up -d
            
            # Execute Laravel commands (Use the container name defined in your compose file)
            docker exec -u root laravel_backend chown -R www-data:www-data /var/www/html/storage
            docker exec laravel_backend php artisan migrate --force